name: GitHub Actions Java test workflow
run-name: Running tests on GitHub Actions

on: [push]

jobs:
  java-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and run tests
        run: |
          cd numbers  # Change to the numbers directory
          mvn clean install
